name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  # JOB 1: BUILD IMAGE
  build-and-push:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      # Fix lỗi lowercase
      - name: Set repository name to lowercase
        run: |
          echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME }}:latest
            ghcr.io/${{ env.REPO_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # JOB 2: DEPLOY LÊN VPS
  deploy:
    runs-on: ubuntu-24.04
    needs: build-and-push
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            cd /srv/m05-fullstack-laravel-react-github-action
            # 1. Kéo tất cả image mới về
            docker compose pull
            
            # 2. Dọn sạch cụm cũ (Xóa sạch container, network của project này)
            # Dùng || true để nếu lần đầu chạy không có gì để down thì vẫn không báo lỗi
            docker compose down || true
            
            # 3. Ép xóa thủ công các container "cứng đầu" nếu lỡ tay chạy docker run ngoài luồng
            docker rm -f frontend backend mongodb caddy || true
            
            # 4. Khởi động lại toàn bộ cụm mới
            docker compose up -d --force-recreate --remove-orphans
            
            # 5. Dọn dẹp rác (image cũ không tag)
            docker image prune -f